name: Code Coverage

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - 2.*
      - 3.*
      - 4.*

jobs:
  coverage:
    uses: mrgoodbytes8667/workflows/.github/workflows/code-coverage.yml@php8.0
    with:
      phpUnitVersion: 9.5