name: Code Coverage

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - 2.*
      - 3.*
      - 4.*
      - 5.*
      - 6.*
      - 7.*

jobs:
  coverage:
    uses: mrgoodbytes8667/workflows/.github/workflows/code-coverage.yml@php8.1-8.3
    with:
      phpUnitVersion: 9.6