name: prerelease

on:
  push:
    tags:
      - 'v*ALPHA*'
      - 'v*BETA*'
      - 'v*RC*'
  workflow_dispatch:

jobs:
  release:
    uses: mrgoodbytes8667/workflows/.github/workflows/release.yml@php8.0-8.1
    with:
      phpUnitVersion: 9.5
      prerelease: true

  trigger_child_tests:
    needs: build
    # The type of runner that the job will run on
    timeout-minutes: 15
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        repo: [ "discord-bundle", "discord-response-bundle", "twitch-client-bundle", "twitch-response-bundle" ]
    steps:
      - name: Trigger Dispatch
        run: |
          curl -X POST --location "https://api.github.com/repos/mrgoodbytes8667/${{ matrix.repo }}/dispatches" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Content-Type: application/x-www-form-urlencoded" \
              -H "Authorization: token ${{ secrets.MY_PAT }}" \
              -d "{\"event_type\":\"parent-repo-push\"}"
