name: Tests By Symfony Version

on:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main
      - 2.*
      - 3.*
      - 4.*
      - 5.*
      - 6.*
      - 7.*

  schedule:
    # Weekly on Thursdays at 3pm UTC
    - cron:  '0 15 * * 4'

jobs:
  symfony64:
    uses: mrgoodbytes8667/workflows/.github/workflows/run-tests-by-version.yml@php8.1-8.3
    with:
      phpUnitVersion: 9.6
      symfony: 6.4

  symfony70:
    uses: mrgoodbytes8667/workflows/.github/workflows/run-tests-by-version.yml@php8.2-8.3
    with:
      phpUnitVersion: 9.6
      symfony: 7.0